//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppServiceDeveloperAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEnrollment
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public bool EmployeeEnrollmentStatus { get; set; }
        public bool EmployeeEnrollmentPrescreeningStatus { get; set; }
        public Nullable<bool> EmployeeFinalAssessmentStatus { get; set; }
    }
}
